# prometheus.yml:
global:
  # collect metrics from targets (the node-exporter) every
  # 15s
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  # Where to find the node-exporter service
  - targets: ['localhost:9100']
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
